# Generated by Django 5.0.1 on 2024-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_for_private_house',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
