# Generated by Django 5.0.1 on 2024-03-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_form_for_private_house_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_for_bisnues',
            name='locality_for_bisnues',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='form_for_bisnues',
            name='name_bisnues',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='form_for_bisnues',
            name='number_for_bisnues',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='form_for_bisnues',
            name='time_create_for_bisnues',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_for_private_house',
            name='apartment_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='form_for_private_house',
            name='first_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='form_for_private_house',
            name='home_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='form_for_private_house',
            name='locality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='form_for_private_house',
            name='name_street',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='form_for_private_house',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='form_for_private_house',
            name='second_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
