# Generated by Django 5.0.1 on 2024-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_form_for_bisnues_locality_for_bisnues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_for_bisnues',
            name='name_bisnues',
            field=models.CharField(default='', max_length=50),
        ),
    ]
